<a href="https://colab.research.google.com/github/algiantara3-ops/Structur-DataD-Pertemuan1/blob/main/latihan_aray_Colab.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Selamat Datang di Colab!

In [13]:
import numpy as np

arr= np.array([10,20,30,40,50])
print (arr)

[10 20 30 40 50]


In [14]:
#import as numpy untuk bekerja dengan array
import numpy as np


In [15]:
# array berisi 10 bilangan ganjil
print ("1. array berisi bilangan ganjil")
# membuat array bilangan ganjil pertama
x= np.array([1,2,3,4,5,6,7,8,9,10])
print(x)

1. array berisi bilangan ganjil
[ 1  2  3  4  5  6  7  8  9 10]


In [16]:
# mencari nilai tertinggi
print ("2. nilai tertingggi")
x= np.array([1,2,3,4,5,6,7,8,9,10])

nilai_tertinggi = np.max(x)
print(x)
print ("x", nilai_tertinggi)

2. nilsi tertingggi
[ 1  2  3  4  5  6  7  8  9 10]
x 10


In [17]:
# mencri nilai terendah
print("3.nilai terendah")
x= np.array([1,2,3,4,5,6,7,8,9,10])
nilai_terendah = np.min(x)
print(x)
print("x", nilai_terendah)

3.nilai terendah
[ 1  2  3  4  5  6  7  8  9 10]
x 1


In [18]:
# mencari rata-rata
print("4.rata-rata")
x= np.array ([1,2,3,4,5,6,7,8,9,10])
rata_rata = np.mean(x)
print(x)
print("x", rata_rata)
#

4.rata-rata
[ 1  2  3  4  5  6  7  8  9 10]
x 5.5
